version : '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./django:/var/www/html
    working_dir: /var/www/html/
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    environment:
      POSTGRES_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    expose:
      - 8000
    depends_on:
      - db

  nginx:
    image:
      nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./django/static:/staticfiles
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
